site_name: 黄品汇APP安装包
site_author: 黄品汇
site_description: 黄品汇APP安装包推荐及独家原创内容，满足不同用户的观影需求。同时提供爱情岛网站会员服务，享受无广告、蓝光画质爱情岛路线等特权，打造沉浸式观影体验。
theme:
  name: readthedocs
nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Contact: contact.md
